server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xsb-server?useSSL=false&serverTimezone=UTC
    username: xsb
    password: xsb-server
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true